In [1]:
!pip install --upgrade pip

/bin/bash: /Users/marianasantos/Desktop/Universidade/Fundamentos de Engenharia de Dados/Exercícios no vs code/Projeto/.venv/bin/pip: /Users/marianasantos/Desktop/Universidade/Projeto/.venv/bin/python3.12: bad interpreter: No such file or directory

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

## Dataset

In [2]:
RAW_PATH = f"../raw/uci-diabetes/dirty/"

In [3]:
df = pd.read_csv(f'{RAW_PATH}diabetes-dirty.csv', sep=';')
df

,Unnamed: 0,Index,Pregnancies,Glucose,Blood Pressure,Skin Thickness,Insulin,Body Mass Index,Diabetes Pedigree Function,Age,Outcome,BMI Category,Clinic Region,Care Path,Patient Segment
0,0,0,6,148.0 mg/dL,72.0,35.0,nan uU/mL,33.6 bmi,0.627,50.0 years,positive,obese,north,high-risk,adult
1,1,1,1,85.0,66.0,29.0,NaN,26.6,0.351,31.0,negative,OVERWEIGHT,SOUTH,ROUTINE FOLLOW-UP,SENIOR
2,2,2,8,183.0,64.0,NaN,NaN,23.3,0.672,32.0,1,normal-weight,N,urgent monitoring,mid-age
3,3,3,1,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0,under wt,south-side,routine,?
4,4,4,0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1,unknown,?,NaN,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
766,766,766,1,126.0,NaN,NaN,?,30.1,0.349,NaN,negative,obese,North,ROUTINE FOLLOW-UP,Adult
767,767,767,1,NaN,70.0,31.0,NaN,30.4,0.315,23.0,positive,normal-weight,South,Routine Follow-up,Adult
768,768,3,1,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0,under wt,south-side,routine,?
769,769,15,7,100.0,NaN,NaN,NaN,30.0,0.484,32.0,1,overweight,South,High Risk,Adult
770,770,27,1,nan mg/dL,NaN,15.0,140.0 uU/mL,23.2 bmi,0.487,22.0 years,0,obese,South,Routine Follow-up,Adult

## Drop unname column

In [4]:
df.drop(columns=['Unnamed: 0'], inplace=True)

## Checking dataset

In [5]:
linhas, colunas = df.shape
print(f'')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 771 entries, 0 to 770
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0    Index                      771 non-null    int64
 1   Pregnancies                 771 non-null    int64
 2    Glucose                    714 non-null    object
 3   Blood Pressure              666 non-null    float64
 4   Skin Thickness              543 non-null    float64
 5   Insulin                     425 non-null    object
 6   Body Mass Index             718 non-null    object
 7   Diabetes Pedigree Function  771 non-null    float64
 8   Age                         709 non-null    object
 9   Outcome                     744 non-null    object
 10  BMI Category                686 non-null    object
 11  Clinic Region               744 non-null    object
 12  Care Path                   721 non-null    object
 13  Patient Segment             744 non-null    object
dtypes: float64(3), int64(2), object(9)
memory usage: 84.5+ KB

In [7]:
df.describe()

,Index,Pregnancies,Blood Pressure,Skin Thickness,Diabetes Pedigree Function
count,771.000000,771.000000,666.000000,543.000000,771.000000
mean,382.066148,3.836576,72.231231,29.116022,0.471516
std,222.601944,3.373966,12.294530,10.478557,0.330866
min,0.000000,-2.000000,24.000000,7.000000,0.078000
25%,189.500000,1.000000,64.000000,22.000000,0.243500
50%,382.000000,3.000000,72.000000,29.000000,0.374000
75%,574.500000,6.000000,80.000000,36.000000,0.625000
max,767.000000,17.000000,122.000000,99.000000,2.420000

## Preprocessing

In [8]:
df.columns

Index([' Index ', 'Pregnancies ', ' Glucose', 'Blood Pressure',
       'Skin Thickness ', 'Insulin', 'Body Mass Index',
       'Diabetes Pedigree Function', 'Age ', 'Outcome ', 'BMI Category',
       'Clinic Region', 'Care Path ', 'Patient Segment'],
      dtype='object')

In [9]:
df.columns = [col.strip().lower() for col in df.columns]

In [10]:
df.columns

Index(['index', 'pregnancies', 'glucose', 'blood pressure', 'skin thickness',
       'insulin', 'body mass index', 'diabetes pedigree function', 'age',
       'outcome', 'bmi category', 'clinic region', 'care path',
       'patient segment'],
      dtype='object')

In [11]:
df = df.drop(['index', 'bmi category'], axis=1)

# Category list & Numerical list

In [12]:
categorical_columns = df.select_dtypes(include='object').columns.tolist()

In [14]:
categorical_columns

['glucose',
 'insulin',
 'body mass index',
 'age',
 'outcome',
 'clinic region',
 'care path',
 'patient segment']

- tem colunas numéricas

In [15]:
categorical_columns = ['outcome', 'clinic region', 'care path', 'patient segment']

In [16]:
numerical_columns = df.select_dtypes(include=np.number).columns.tolist()
numerical_columns

['pregnancies',
 'blood pressure',
 'skin thickness',
 'diabetes pedigree function']

- falta colunas

In [17]:
numerical_columns = ['pregnancies', 'glucose', 'blood pressure', 'skin thickness', 'insulin', 'body mass index', 'diabetes pedigree function', 'age']

#### Inspect unique values

In [19]:
for col in categorical_columns:
    print(df[col].value_counts(), end= '\n\n')
    print(df[col].unique())
    print('-------------------')

outcome
0             403
1             201
positive       48
 negative      39
1              37
?              16
Name: count, dtype: int64

['positive' ' negative ' '1 ' '0' '1' '?' nan]
-------------------
clinic region
South         264
North         232
north          78
SOUTH          65
N              51
south-side     34
 ?             20
Name: count, dtype: int64

['north ' 'SOUTH' 'N' 'south-side' ' ?' 'South' 'North' nan]
-------------------
care path
Routine Follow-up    304
High Risk            161
high-risk             76
ROUTINE FOLLOW-UP     75
urgent monitoring     62
routine               43
Name: count, dtype: int64

['high-risk' 'ROUTINE FOLLOW-UP' 'urgent monitoring' 'routine ' nan
 'Routine Follow-up' 'High Risk']
-------------------
patient segment
Adult      389
adult      105
SENIOR      80
Senior      66
mid-age     63
 ?          41
Name: count, dtype: int64

['adult ' 'SENIOR' 'mid-age' ' ?' 'Adult' nan 'Senior']
-------------------

#### Replace inconsistent missing markers with `NaN`

In [27]:
df['outcome'] = df['outcome'].replace(['?'], np.nan)

df['clinic region'] = df['clinic region'].replace([' ?'], np.nan)

df['patient segment'] = df['patient segment'].replace([' ?'], np.nan)

#### Check for missing values

In [21]:
df.isnull().sum()

pregnancies                     0
glucose                        57
blood pressure                105
skin thickness                228
insulin                       346
body mass index                53
diabetes pedigree function      0
age                            62
outcome                        27
clinic region                  47
care path                      50
patient segment                68
dtype: int64

In [22]:
print("Colunas mais problemáticas:")
missing = df.isnull().sum()
print(missing[missing > 0].sort_values(ascending=False))

Colunas mais problemáticas:
insulin            346
skin thickness     228
blood pressure     105
patient segment     68
age                 62
glucose             57
body mass index     53
care path           50
clinic region       47
outcome             27
dtype: int64

In [23]:
def percentage_missing_values(df: pd.DataFrame, col: str) -> float:
    # Calcula a contagem de valores nulos na coluna específica
    missing_count = df[col].isnull().sum()
    
    # Calcula o total de linhas do DataFrame
    total_rows = len(df)
    
    # Calcula a porcentagem
    percentage = (missing_count / total_rows) * 100
    
    return percentage

In [24]:

insulin  = percentage_missing_values(df, 'insulin')
print(f"Percentagem de valores faltantes em 'insulin': {insulin:.2f}%")

skin_thickness = percentage_missing_values(df, 'skin thickness')
print(f"Percentagem de valores faltantes em 'skin thickness': {skin_thickness:.2f}%")

blood_pressure = percentage_missing_values(df, 'blood pressure')
print(f"Percentagem de valores faltantes em 'blood pressure': {blood_pressure:.2f}%")

patient_segment = percentage_missing_values(df, 'patient segment')
print(f"Percentagem de valores faltantes em 'patient segment': {patient_segment:.2f}%")

age = percentage_missing_values(df, 'age')
print(f"Percentagem de valores faltantes em 'age': {age:.2f}%")

glucose = percentage_missing_values(df, 'glucose')
print(f"Percentagem de valores faltantes em 'glucose': {glucose:.2f}%")

body_mass_index = percentage_missing_values(df, 'body mass index')
print(f"Percentagem de valores faltantes em 'body mass index': {body_mass_index:.2f}%")

care_path = percentage_missing_values(df, 'care path')
print(f"Percentagem de valores faltantes em 'care path': {care_path:.2f}%")

clinic_region = percentage_missing_values(df, 'clinic region')
print(f"Percentagem de valores faltantes em 'care path': {clinic_region:.2f}%")

outcome = percentage_missing_values(df, 'outcome')
print(f"Percentagem de valores faltantes em 'outcome': {outcome:.2f}%")

Percentagem de valores faltantes em 'insulin': 44.88%
Percentagem de valores faltantes em 'skin thickness': 29.57%
Percentagem de valores faltantes em 'blood pressure': 13.62%
Percentagem de valores faltantes em 'patient segment': 8.82%
Percentagem de valores faltantes em 'age': 8.04%
Percentagem de valores faltantes em 'glucose': 7.39%
Percentagem de valores faltantes em 'body mass index': 6.87%
Percentagem de valores faltantes em 'care path': 6.49%
Percentagem de valores faltantes em 'care path': 6.10%
Percentagem de valores faltantes em 'outcome': 3.50%

In [28]:
for col in categorical_columns:
    print(df[col].value_counts(), end= '\n\n')
    print(df[col].unique())
    print('-------------------')

outcome
0             403
1             201
positive       48
 negative      39
1              37
Name: count, dtype: int64

['positive' ' negative ' '1 ' '0' '1' nan]
-------------------
clinic region
South         264
North         232
north          78
SOUTH          65
N              51
south-side     34
Name: count, dtype: int64

['north ' 'SOUTH' 'N' 'south-side' nan 'South' 'North']
-------------------
care path
Routine Follow-up    304
High Risk            161
high-risk             76
ROUTINE FOLLOW-UP     75
urgent monitoring     62
routine               43
Name: count, dtype: int64

['high-risk' 'ROUTINE FOLLOW-UP' 'urgent monitoring' 'routine ' nan
 'Routine Follow-up' 'High Risk']
-------------------
patient segment
Adult      389
adult      105
SENIOR      80
Senior      66
mid-age     63
Name: count, dtype: int64

['adult ' 'SENIOR' 'mid-age' nan 'Adult' 'Senior']
-------------------

#### Standardizing values

In [29]:
def standardize_outcome(val):
    val = str(val).strip().lower()
    if val == '1' or val == 'positive':
        return 'Positive'
    elif val == '0' or val == 'negative':
        return 'Negative'
    else:
        return np.nan
    
def standardize_clinic_region(val):
    val = str(val).strip().lower()
    if val == 'north' or val == 'n':
        return 'North'
    elif val == 'south' or val == 'south-side':
        return 'South'
    else:
        return np.nan

def standardize_care_path(val):
    val = str(val).strip().lower()
    if val == 'routine follow-up' or val == 'routine':
        return 'Routine Follow-up'
    elif val == 'high-risk':
        return 'High-Risk'
    elif val == 'urgent monitoring':
        return 'Urgent Monitoring'
    else:
        return np.nan

def standardize_patient_segment(val):
    val = str(val).strip().lower()
    if val == 'adult':
        return 'Adult'
    elif val == 'senior':
        return 'Senior'
    elif val == 'mid-age':
        return 'Mid-Age'
    else:
        return np.nan

In [ ]:
# Applying functions
df['outcome'] = df['outcome'].apply(standardize_outcome)
df['clinic region'] = df['clinic region'].apply(standardize_clinic_region)
df['care path'] = df['care path'].apply(standardize_care_path)
df['patient segment'] = df['patient segment'].apply(standardize_patient_segment)

In [32]:
for col in categorical_columns:
    print(df[col].value_counts(), end= '\n\n')
    print(df[col].unique())
    print('-------------------')

outcome
Negative    442
Positive    286
Name: count, dtype: int64

['Positive' 'Negative' nan]
-------------------
clinic region
South    363
North    361
Name: count, dtype: int64

['North' 'South' nan]
-------------------
care path
Routine Follow-up    422
High-Risk             76
Urgent Monitoring     62
Name: count, dtype: int64

['High-Risk' 'Routine Follow-up' 'Urgent Monitoring' nan]
-------------------
patient segment
Adult      494
Senior     146
Mid-Age     63
Name: count, dtype: int64

['Adult' 'Senior' 'Mid-Age' nan]
-------------------

# Fixing column types

In [33]:
for col in numerical_columns:
    print(df[col].value_counts(), end= '\n\n')
    print(df[col].unique())
    print('-------------------')

pregnancies
 1     137
 0     111
 2     102
 3      75
 4      68
 5      57
 6      50
 7      46
 8      38
 9      28
 10     24
 11     11
 13     10
 12      9
 14      2
-2       1
 15      1
 17      1
Name: count, dtype: int64

[ 6  1  8  0  5  3 10  2  4  7  9 11 13 -2 15 17 12 14]
-------------------
glucose
 ?             19
99.0           17
100.0          15
129.0          13
105.0          12
               ..
178.0           1
61.0            1
270.0           1
156.0 mg/dL     1
190.0           1
Name: count, Length: 174, dtype: int64

['148.0 mg/dL' '85.0' '183.0' '89.0' '137.0' ' ?' '78.0' '115.0' '197.0'
 '125.0' '999 mg/dL' '168.0' '139.0' '189.0' '166.0' '100.0' '118.0' nan
 '103.0' '126.0' '99.0' '196.0' '119.0' '143.0' '147.0' 'nan mg/dL'
 '145.0' '117.0' '109.0' '158.0' '88.0' '92.0' '122.0' '138.0' '102.0'
 '90.0' '111.0' '180.0' '133.0' '106.0' '171.0' '159.0' '71.0' '105.0'
 '528.0' '150.0 mg/dL' '73.0' '187.0' '146.0' '84.0' '399.0' '44.0'
 '141.0' '114.0' '129.0' '62.0' '95.0' '131.0' '112.0' '113.0'
 '74.0 mg/dL' '83.0' '101.0' '110.0' '136.0' '107.0' '80.0' '123.0' '81.0'
 '134.0' '142.0' '144.0' '279.0' '163.0' '151.0' '96.0' '83.0 mg/dL'
 '155.0' '76.0' '160.0' '124.0' '97.0' '162.0' '132.0' '120.0' '173.0'
 '170.0' '93.0' '384.0' '108.0' '154.0' '57.0' '156.0' '153.0' '188.0'
 '152.0' '114.0 mg/dL' '104.0' '148.0' '87.0' '79.0' '75.0' '130.0'
 '194.0' '181.0' '128.0' '139.0 mg/dL' '135.0' '324.0' '184.0' '179.0'
 '140.0' '109.0 mg/dL' '177.0' '74.0' '513.0' '543.0' '91.0' '417.0'
 '119.0 mg/dL' '165.0' '86.0' '191.0' '161.0' '126.0 mg/dL' '501.0' '77.0'
 '150.0' '182.0' '456.0' '112.0 mg/dL' '157.0' '178.0' '116.0'
 '137.0 mg/dL' '61.0' '270.0' '98.0' '156.0 mg/dL' '127.0' '82.0' '193.0'
 '72.0' '123.0 mg/dL' '172.0' '94.0' '80.0 mg/dL' '175.0' '134.0 mg/dL'
 '195.0' '91.0 mg/dL' '68.0' '100.0 mg/dL' '252.0' '186.0' '164.0' '567.0'
 '198.0' '121.0' '363.0' '176.0' '67.0' '174.0' '92.0 mg/dL' '309.0'
 '136.0 mg/dL' '167.0' '195.0 mg/dL' '169.0' '366.0' '375.0' '402.0'
 '65.0' '459.0' '190.0']
-------------------
blood pressure
70.0     51
74.0     50
78.0     44
72.0     41
64.0     40
68.0     39
80.0     36
76.0     35
60.0     33
62.0     30
66.0     27
82.0     24
88.0     23
84.0     21
58.0     20
90.0     20
86.0     20
56.0     12
54.0     11
50.0     11
52.0     10
65.0      7
75.0      6
92.0      6
94.0      6
85.0      5
48.0      5
96.0      4
106.0     3
98.0      3
44.0      3
30.0      2
46.0      2
104.0     2
108.0     2
55.0      2
110.0     1
95.0      1
122.0     1
102.0     1
100.0     1
61.0      1
24.0      1
38.0      1
40.0      1
114.0     1
Name: count, dtype: int64

[ 72.  66.  64.  40.  74.  nan  70.  96.  80.  60.  84.  30.  88.  90.
  94.  92.  75.  76.  58.  78.  68.  56.  50.  82.  62.  85.  86.  48.
  65. 108.  55. 122.  54.  52. 110.  98. 104.  95.  46. 102. 100.  61.
  44.  24.  38. 106. 114.]
-------------------
skin thickness
32.0    31
30.0    27
23.0    23
27.0    23
28.0    20
33.0    20
18.0    20
31.0    19
19.0    18
39.0    18
29.0    17
25.0    16
37.0    16
40.0    16
22.0    16
26.0    16
35.0    15
15.0    15
41.0    15
36.0    14
17.0    14
20.0    13
24.0    12
42.0    11
13.0    11
21.0    10
46.0     8
34.0     8
12.0     7
38.0     7
45.0     6
16.0     6
43.0     6
11.0     6
14.0     6
44.0     5
10.0     5
47.0     4
48.0     4
50.0     3
49.0     3
54.0     2
7.0      2
52.0     2
8.0      2
56.0     1
51.0     1
60.0     1
63.0     1
99.0     1
Name: count, dtype: int64

[35. 29. nan 23. 32. 45. 19. 47. 38. 30. 41. 33. 26. 15. 36. 11. 31. 37.
 42. 25. 18. 24. 39. 27. 21. 34. 10. 60. 13. 20. 22. 28. 54. 40. 51. 56.
 14. 17. 50. 44. 12. 46. 16.  7. 52. 43. 48.  8. 49. 63. 99.]
-------------------
insulin
?            28
 ?           19
nan uU/mL    11
105.0         9
130.0         8
             ..
228.0         1
320.0         1
108.0         1
73.0          1
112.0         1
Name: count, Length: 194, dtype: int64

['nan uU/mL' nan '94.0' '168.0' ' ?' '88.0' '543.0' '846.0' '175.0'
 '230.0' '83.0' '96.0' '?' '146.0' '115.0' '140.0 uU/mL' '110.0' '245.0'
 '54.0' '192.0' '207.0' '70.0' '240.0' '82.0' '36.0' '23.0' '1500.0'
 '342.0 uU/mL' '304.0' '142.0' '128.0' '100.0' '90.0' '140.0' '270.0'
 '71.0' '125.0' '176.0' '48.0' '64.0' '228.0' '76.0' '320.0' '40.0'
 '152.0' '18.0 uU/mL' '135.0' '495.0' '37.0' '51.0' '99.0' '225.0' '49.0'
 '50.0' '92.0' '325.0' '63.0' '284.0' '119.0' '204.0' '155.0' '485.0'
 '114.0' '105.0' '285.0 uU/mL' '156.0' '130.0' '55.0' '58.0' '160.0 uU/mL'
 '210.0' '318.0' '44.0' '190.0' '280.0' '87.0' '271.0' '129.0 uU/mL'
 '120.0' '478.0' '56.0' '32.0' '744.0' '53.0' '45.0' '176.0 uU/mL' '194.0'
 '680.0' '402.0' '258.0' '150.0' '67.0' '57.0' '116.0' '278.0' '122.0'
 '545.0' '220.0' '74.0' '360.0' '215.0 uU/mL' '184.0' '42.0' '132.0'
 '148.0' '180.0' '205.0' '85.0' '231.0' '145.0' '68.0' '52.0' '255.0'
 '73.0' '108.0' '215.0' '167.0' '249.0' '293.0' '66.0' '465.0' '89.0'
 '84.0' '75.0' '72.0' '182.0' '59.0' '285.0' '81.0' '196.0' '415.0'
 '275.0' '165.0 uU/mL' '579.0' '310.0' '61.0' '170.0' '78.0' '277.0'
 '60.0 uU/mL' '14.0' '95.0' '237.0' '191.0' '328.0' '250.0' '480.0 uU/mL'
 '265.0' '193.0' '79.0' '86.0' '165.0' '326.0' '188.0' '106.0' '65.0'
 '166.0' '274.0' '77.0' '18.0' '126.0 uU/mL' '126.0' '330.0' '600.0'
 '230.0 uU/mL' '185.0' '25.0' '41.0' '1360.0' '158.0' '321.0' '144.0'
 '15.0' '183.0' '91.0' '46.0' '760.0' '440.0' '159.0' '130.0 uU/mL'
 '540.0' '200.0' '480.0' '1000.0' '160.0' '387.0' '22.0' '1455.0' '392.0'
 '178.0' '127.0' '370.0' '510.0' '16.0' '112.0']
-------------------
body mass index
 ?        19
31.2      10
33.3      10
32.8       9
32.0       9
          ..
23.0       1
 27.8      1
24.9       1
27.0       1
 28.4      1
Name: count, Length: 339, dtype: int64

['33.6 bmi' '26.6' '23.3' ' 28.1 ' '43.1' ' ?' '31.0' '35.3' ' 30.5 ' nan
 '37.6' '38.0' '27.1' '30.1' '25.8' '30.0' ' 45.8 ' '29.6' '43.3' ' 34.6 '
 '39.3' '35.4' '39.8' ' 29.0 ' '36.6' '-5 bmi' '39.4' '23.2 bmi' '22.2'
 '34.1' '36.0' '24.8' '19.9' '27.6' '24.0' '33.2' '32.9' '38.2' '37.1'
 '34.0' '40.2' '22.7' '45.4' '27.4' '42.0' ' 28.0 ' '39.1' ' 19.4 ' '24.2'
 '24.4' '84.25' '34.7 bmi' ' 37.7 ' '46.8' '40.5' ' 41.5 ' ' nan ' '82.25'
 '25.0' '25.4' '32.8' '29.0' '32.5' '42.7' '19.6' ' 28.9 ' '28.6' '43.4'
 '35.1' '32.0' '24.7' '32.6' '37.7' '43.2' ' nan  bmi' '29.3' ' 48.8 '
 ' 32.4 ' '26.5' ' 19.1 ' '46.7' '23.8' '33.9' '31.6' '20.4' '71.75'
 '49.7' '39.0' ' 26.1 ' '22.5' '39.6' '28.7' '22.4' '29.5' '34.3 bmi'
 '37.4' '33.3' ' 34.0 ' '31.2' '30.5' ' 33.7 ' '28.2' '23.2' ' 53.2 '
 '34.2' '33.6' '55.0' '42.9' '27.9' '29.7' '38.3' ' 21.1 ' ' 33.8  bmi'
 '30.8' '36.9' '52.75' '39.5' '32.4' '27.3' '21.9' '34.3' '40.6' '47.9'
 '50.0' '24.6' '25.2' ' 40.9 ' '37.2' '44.2 bmi' '29.9' '31.9' '28.9'
 '43.5' ' 32.7 ' '67.1' '45.0' ' 34.9 ' '27.7' '26.8' '35.9' ' 32.0 '
 'nan bmi' '22.6' '33.1' '52.3' '24.3' '22.9' '34.8' '30.9' ' 40.1 '
 '68.25' '23.9' '35.5' '42.8' '42.6' '41.8' '35.8 bmi' '37.8' '34.6'
 '28.8' ' 23.6 ' '35.7' '36.7' '44.0' ' 35.0 ' '109.0' '89.75' '44.1'
 ' 30.8 ' '18.4' '29.2' '64.0' '27.1 bmi' ' 33.6 ' '25.9' ' 32.1 ' '36.3'
 '40.0' '25.1' '27.5' '23.0' ' 27.8 ' '24.9' '25.3' '37.9' '30.4' '27.0'
 ' 26.0 ' ' 38.7 ' '45.6' '20.8' '28.0' '30.7 bmi' '35.8' '52.9' '39.7'
 '25.5' '26.2' ' 39.4 ' '19.3' '38.1' '23.5' ' 27.5 ' '67.0' '35.7 bmi'
 '25.6' '45.5' '23.1' '32.7' ' 23.9 ' ' 47.9 ' '33.8' '39.9' ' 25.9 '
 '34.7' '36.8' '38.5' '21.8' ' 41.0 ' ' 42.2 ' '31.2 bmi' ' 34.4 ' '68.0'
 ' 30.4 ' ' 35.3 ' '36.5' '29.8' '34.9' '21.0' '38.4' '39.2' '48.3 bmi'
 '20.0' ' 25.4 ' ' 22.3 ' '32.3' '45.7' '22.1' ' 32.9 ' '21.1' '35.0'
 '42.1 bmi' '42.4' '27.2' '18.2' '26.4' '45.3' '37.0' ' 40.6 ' ' 22.2 '
 '30.0 bmi' '24.5' ' 37.4 ' ' 29.9 ' '32.2' ' 33.2 ' ' 59.4 ' '21.2'
 ' 39.9 ' ' 25.9  bmi' ' 27.6 ' '27.8' '46.1' '41.3' ' 38.8 ' '33.7'
 '44.2' '42.3' '46.5' '26.1' '33.5' '26.0' ' 39.0 ' '37.3' ' 28.6 '
 '27.3 bmi' ' 30.3 ' ' 26.3 ' ' 29.8 ' '21.7' '36.4' '39.4 bmi' '34.5'
 '43.6' '71.25' ' 38.1 ' ' 46.2 ' '26.9' '38.6' ' 32.0  bmi' '31.3'
 ' 42.9 ' '42.1' '66.25' '38.7' ' 46.8 ' '34.4' '67.75' '23.7' '35.2'
 '28.4' '19.5' '103.75' ' 36.1 ' '20.1' '24.2 bmi' '40.8' ' 34.5 '
 ' 31.6 ' '40.9' ' 29.3 ' '69.0' ' 23.4 ' '28.3 bmi' '57.3' '35.6'
 '30.9 bmi' ' 24.2 ' '49.6' '44.6' '28.3' '24.1' ' 46.1 ' ' 38.5 '
 ' 44.5 ' ' 29.6 ' '41.2' '66.0' '30.1 bmi' '44.5' ' 28.5 ' '101.5' '49.3'
 ' 46.3 ' ' 31.2 ' '97.5' ' 43.3 ' ' 36.3 ' '37.5' ' 28.4 ']
-------------------
diabetes pedigree function
0.254    6
0.258    6
0.261    5
0.167    5
0.268    5
        ..
1.353    1
0.655    1
0.092    1
0.926    1
0.171    1
Name: count, Length: 517, dtype: int64

[0.627 0.351 0.672 0.167 2.288 0.201 0.248 0.134 0.158 0.232 0.191 0.537
 1.441 0.398 0.587 0.484 0.551 0.254 0.183 0.529 0.704 0.388 0.451 0.263
 0.205 0.257 0.487 0.245 0.337 0.546 0.851 0.267 0.188 0.512 0.966 0.42
 0.665 0.503 1.39  0.271 0.696 0.235 0.721 0.294 1.893 0.564 0.586 0.344
 0.305 0.491 0.526 0.342 0.467 0.718 0.962 1.781 0.173 0.304 0.27  0.699
 0.258 0.203 0.855 0.845 0.334 0.189 0.867 0.411 0.583 0.231 0.396 0.14
 0.391 0.37  0.307 0.102 0.767 0.237 0.227 0.698 0.178 0.324 0.153 0.165
 0.443 0.261 0.277 0.761 0.255 0.13  0.323 0.356 0.325 1.222 0.179 0.262
 0.283 0.93  0.801 0.207 0.287 0.336 0.247 0.199 0.543 0.192 0.588 0.539
 0.22  0.654 0.223 0.759 0.26  0.404 0.186 0.278 0.496 0.452 0.403 0.741
 0.361 1.114 0.457 0.647 0.088 0.597 0.532 0.703 0.159 0.268 0.286 0.318
 0.272 0.572 0.096 1.4   0.218 0.085 0.399 0.432 1.189 0.687 0.137 0.637
 0.833 0.229 0.817 0.204 0.368 0.743 0.722 0.256 0.709 0.471 0.495 0.18
 0.542 0.773 0.678 0.719 0.382 0.319 0.19  0.956 0.084 0.725 0.299 0.244
 0.745 0.615 1.321 0.64  0.142 0.374 0.383 0.578 0.136 0.395 0.187 0.905
 0.15  0.874 0.236 0.787 0.407 0.605 0.151 0.289 0.355 0.29  0.375 0.164
 0.431 0.742 0.514 0.464 1.224 1.072 0.805 0.209 0.666 0.101 0.198 0.652
 2.329 0.089 0.645 0.238 0.394 0.293 0.479 0.686 0.831 0.582 0.446 0.402
 1.318 0.329 1.213 0.427 0.282 0.143 0.38  0.284 0.249 0.926 0.557 0.092
 0.655 1.353 0.612 0.2   0.226 0.997 0.933 1.101 0.078 0.24  1.136 0.128
 0.422 0.251 0.677 0.296 0.454 0.744 0.881 0.28  0.259 0.619 0.808 0.34
 0.434 0.757 0.613 0.692 0.52  0.412 0.84  0.839 0.156 0.215 0.326 1.391
 0.875 0.313 0.433 0.626 1.127 0.315 0.345 0.129 0.527 0.197 0.731 0.148
 0.123 0.127 0.122 1.476 0.166 0.932 0.343 0.893 0.331 0.472 0.673 0.389
 0.485 0.349 0.279 0.346 0.252 0.243 0.58  0.559 0.302 0.569 0.378 0.385
 0.499 0.306 0.234 2.137 1.731 0.545 0.225 0.816 0.528 0.509 1.021 0.821
 0.947 1.268 0.221 0.66  0.239 0.949 0.444 0.463 0.803 1.6   0.944 0.196
 0.241 0.161 0.135 0.376 1.191 0.702 0.674 1.076 0.534 1.095 0.554 0.624
 0.219 0.507 0.561 0.421 0.516 0.264 0.328 0.233 0.108 1.138 0.147 0.727
 0.435 0.497 0.23  0.955 2.42  0.658 0.33  0.51  0.285 0.415 0.381 0.832
 0.498 0.212 0.364 1.001 0.46  0.733 0.416 0.705 1.022 0.269 0.6   0.571
 0.607 0.17  0.21  0.126 0.711 0.466 0.162 0.419 0.63  0.365 0.536 1.159
 0.629 0.292 0.145 1.144 0.174 0.547 0.163 0.738 0.314 0.968 0.409 0.297
 0.525 0.154 0.771 0.107 0.493 0.717 0.917 0.501 1.251 0.735 0.804 0.661
 0.549 0.825 0.423 1.034 0.16  0.341 0.68  0.591 0.3   0.121 0.502 0.401
 0.601 0.748 0.338 0.43  0.892 0.813 0.693 0.575 0.371 0.206 0.417 1.154
 0.925 0.175 1.699 0.682 0.194 0.4   0.1   1.258 0.482 0.138 0.593 0.878
 0.157 1.282 0.141 0.246 1.698 1.461 0.347 0.362 0.393 0.144 0.732 0.115
 0.465 0.649 0.871 0.149 0.695 0.303 0.61  0.73  0.447 0.455 0.133 0.155
 1.162 1.292 0.182 1.394 0.217 0.631 0.88  0.614 0.332 0.366 0.181 0.828
 0.335 0.856 0.886 0.439 0.253 0.598 0.904 0.483 0.565 0.118 0.177 0.176
 0.295 0.441 0.352 0.826 0.97  0.595 0.317 0.265 0.646 0.426 0.56  0.515
 0.453 0.785 0.734 1.174 0.488 0.358 1.096 0.408 1.182 0.222 1.057 0.766
 0.171]
-------------------
age
21.0          56
22.0          56
24.0          39
25.0          38
26.0          31
              ..
21.0 years     1
30.0 years     1
552.0          1
32.0 years     1
39.0 years     1
Name: count, Length: 95, dtype: int64

['50.0 years' '31.0' '32.0' '21.0' '33.0' '30.0' '26.0' nan '53.0' '54.0'
 '34.0' '57.0' '59.0' '51.0' '396.0' '27.0' '50.0' '41.0' '29.0' '43.0'
 '22.0 years' '38.0' '720.0' '28.0' '22.0' '45.0' '35.0' '56.0' '48.0'
 '150' '24.0' '58.0' '42.0 years' '492.0' '44.0' '39.0' '36.0' '42.0'
 '25.0' '23.0' '37.0' '60.0' '40.0' '25.0 years' '46.0' '61.0' '69.0'
 '276.0' '360.0' '62.0' '31.0 years' '55.0' '65.0' '47.0' '27.0 years'
 '52.0' '384.0' '66.0' '33.0 years' '49.0' '63.0' '38.0 years' '480.0'
 '624.0' '564.0' '372.0' '24.0 years' '420.0' '348.0' '21.0 years'
 '30.0 years' '552.0' '336.0' '32.0 years' '26.0 years' '264.0' '516.0'
 '312.0' '72.0' '81.0 years' '252.0 years' '67.0' '252.0' '300.0'
 '43.0 years' '444.0' '46.0 years' '34.0 years' '288.0' '28.0 years'
 '70.0' '68.0' '408.0' '52.0 years' '540.0' '39.0 years']
-------------------

In [34]:
def clean_numeric_pollution(df, columns):
    for col in columns:
    
        df[col] = df[col].astype(str).str.extract('(\d+)').astype(float)
        
        df[col] = df[col].astype('Int64')
    return df

df = clean_numeric_pollution(df, numerical_columns)

<>:4: SyntaxWarning: invalid escape sequence '\d'
<>:4: SyntaxWarning: invalid escape sequence '\d'
/var/folders/rc/98dfkj2x429dbn7n7sx100200000gp/T/ipykernel_90184/4283555489.py:4: SyntaxWarning: invalid escape sequence '\d'
  df[col] = df[col].astype(str).str.extract('(\d+)').astype(float)

In [36]:
# checking
for col in numerical_columns:
    print(df[col].value_counts(), end= '\n\n')
    print(df[col].unique())
    print('-------------------')

pregnancies
1     137
0     111
2     103
3      75
4      68
5      57
6      50
7      46
8      38
9      28
10     24
11     11
13     10
12      9
14      2
15      1
17      1
Name: count, dtype: Int64

<IntegerArray>
[6, 1, 8, 0, 5, 3, 10, 2, 4, 7, 9, 11, 13, 15, 17, 12, 14]
Length: 17, dtype: Int64
-------------------
glucose
99     17
100    16
129    13
111    12
105    12
       ..
182     1
178     1
61      1
270     1
190     1
Name: count, Length: 152, dtype: Int64

<IntegerArray>
[ 148,   85,  183,   89,  137, <NA>,   78,  115,  197,  125,
 ...
  174,  309,  167,  169,  366,  375,  402,   65,  459,  190]
Length: 153, dtype: Int64
-------------------
blood pressure
70     51
74     50
78     44
72     41
64     40
68     39
80     36
76     35
60     33
62     30
66     27
82     24
88     23
84     21
58     20
90     20
86     20
56     12
54     11
50     11
52     10
65      7
75      6
92      6
94      6
85      5
48      5
96      4
106     3
98      3
44      3
30      2
46      2
104     2
108     2
55      2
110     1
95      1
122     1
102     1
100     1
61      1
24      1
38      1
40      1
114     1
Name: count, dtype: Int64

<IntegerArray>
[  72,   66,   64,   40,   74, <NA>,   70,   96,   80,   60,   84,   30,   88,
   90,   94,   92,   75,   76,   58,   78,   68,   56,   50,   82,   62,   85,
   86,   48,   65,  108,   55,  122,   54,   52,  110,   98,  104,   95,   46,
  102,  100,   61,   44,   24,   38,  106,  114]
Length: 47, dtype: Int64
-------------------
skin thickness
32    31
30    27
23    23
27    23
28    20
33    20
18    20
31    19
19    18
39    18
29    17
25    16
37    16
40    16
22    16
26    16
35    15
15    15
41    15
36    14
17    14
20    13
24    12
42    11
13    11
21    10
46     8
34     8
12     7
38     7
45     6
16     6
43     6
11     6
14     6
44     5
10     5
47     4
48     4
50     3
49     3
54     2
7      2
52     2
8      2
56     1
51     1
60     1
63     1
99     1
Name: count, dtype: Int64

<IntegerArray>
[  35,   29, <NA>,   23,   32,   45,   19,   47,   38,   30,   41,   33,   26,
   15,   36,   11,   31,   37,   42,   25,   18,   24,   39,   27,   21,   34,
   10,   60,   13,   20,   22,   28,   54,   40,   51,   56,   14,   17,   50,
   44,   12,   46,   16,    7,   52,   43,   48,    8,   49,   63,   99]
Length: 51, dtype: Int64
-------------------
insulin
130    9
105    9
140    9
94     8
120    7
      ..
220    1
278    1
258    1
402    1
112    1
Name: count, Length: 180, dtype: Int64

<IntegerArray>
[<NA>,   94,  168,   88,  543,  846,  175,  230,   83,   96,
 ...
  387,   22, 1455,  392,  178,  127,  370,  510,   16,  112]
Length: 181, dtype: Int64
-------------------
body mass index
32     53
30     45
34     45
33     39
29     34
25     33
35     32
27     32
24     31
28     31
36     27
37     26
31     24
23     22
26     22
39     20
38     20
42     15
21     14
40     13
22     12
43     10
45      9
19      9
46      8
44      7
41      7
20      6
52      4
18      4
49      3
67      3
71      2
69      2
47      2
66      2
48      2
68      2
89      2
101     1
57      1
64      1
103     1
59      1
82      1
109     1
5       1
50      1
84      1
55      1
53      1
97      1
Name: count, dtype: Int64

<IntegerArray>
[  33,   26,   23,   28,   43, <NA>,   31,   35,   30,   37,   38,   27,   25,
   45,   29,   34,   39,   36,    5,   22,   24,   19,   32,   40,   42,   84,
   46,   41,   82,   48,   20,   71,   49,   53,   55,   21,   52,   47,   50,
   44,   67,   68,  109,   89,   18,   64,   59,   66,  103,   69,   57,  101,
   97]
Length: 53, dtype: Int64
-------------------
diabetes pedigree function
0    720
1     47
2      4
Name: count, dtype: Int64

<IntegerArray>
[0, 2, 1]
Length: 3, dtype: Int64
-------------------
age
22     62
21     57
25     41
24     40
26     32
       ..
150     1
480     1
720     1
384     1
540     1
Name: count, Length: 75, dtype: Int64

<IntegerArray>
[  50,   31,   32,   21,   33,   30,   26, <NA>,   53,   54,   34,   57,   59,
   51,  396,   27,   41,   29,   43,   22,   38,  720,   28,   45,   35,   56,
   48,  150,   24,   58,   42,  492,   44,   39,   36,   25,   23,   37,   60,
   40,   46,   61,   69,  276,  360,   62,   55,   65,   47,   52,  384,   66,
   49,   63,  480,  624,  564,  372,  420,  348,  552,  336,  264,  516,  312,
   72,   81,  252,   67,  300,  444,  288,   70,   68,  408,  540]
Length: 76, dtype: Int64
-------------------

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 771 entries, 0 to 770
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   pregnancies                 771 non-null    Int64
 1   glucose                     689 non-null    Int64
 2   blood pressure              666 non-null    Int64
 3   skin thickness              543 non-null    Int64
 4   insulin                     367 non-null    Int64
 5   body mass index             687 non-null    Int64
 6   diabetes pedigree function  771 non-null    Int64
 7   age                         709 non-null    Int64
 8   outcome                     728 non-null    object
 9   clinic region               724 non-null    object
 10  care path                   560 non-null    object
 11  patient segment             703 non-null    object
dtypes: Int64(8), object(4)
memory usage: 78.4+ KB

#  Missing value imputation

#### Impute missing values for numerical columns

In [37]:
df[numerical_columns] = df[numerical_columns].fillna(df[numerical_columns].median())

#### Impute missing values for categorical columns

In [38]:
# Verify whether missing values still exist
df.isnull().sum()

pregnancies                     0
glucose                         0
blood pressure                  0
skin thickness                  0
insulin                         0
body mass index                 0
diabetes pedigree function      0
age                             0
outcome                        43
clinic region                  47
care path                     211
patient segment                68
dtype: int64

In [39]:
def impute_categorical(df, columns):
    for col in columns:
        mode = df[col].mode()
        if len(mode) > 0:
            df[col] = df[col].fillna(mode[0])
        else:
            df[col] = df[col].fillna('unknown')
    return df

df = impute_categorical(df, categorical_columns)

In [40]:
df.isnull().sum()

pregnancies                   0
glucose                       0
blood pressure                0
skin thickness                0
insulin                       0
body mass index               0
diabetes pedigree function    0
age                           0
outcome                       0
clinic region                 0
care path                     0
patient segment               0
dtype: int64

# Duplicates and outliers

In [41]:
dups = df.duplicated().sum()
print(f"Total de linhas duplicadas no df: {dups}")

Total de linhas duplicadas no df: 3

In [42]:
if dups > 0:
    print("Linhas duplicadas:")
    # Mostra as linhas que são cópias umas das outras
    display(df[df.duplicated(keep=False)].sort_values(by=list(df.columns)))

Linhas duplicadas:

,pregnancies,glucose,blood pressure,skin thickness,insulin,body mass index,diabetes pedigree function,age,outcome,clinic region,care path,patient segment
3,1,89,66,23,94,28,0,21,Negative,South,Routine Follow-up,Adult
768,1,89,66,23,94,28,0,21,Negative,South,Routine Follow-up,Adult
27,1,119,72,15,140,23,0,22,Negative,South,Routine Follow-up,Adult
770,1,119,72,15,140,23,0,22,Negative,South,Routine Follow-up,Adult
15,7,100,72,29,126,30,0,32,Positive,South,Routine Follow-up,Adult
769,7,100,72,29,126,30,0,32,Positive,South,Routine Follow-up,Adult

In [43]:
#### Remove duplicated rows 
df = df.drop_duplicates()

### Verifying if there are **outliers** in numerical columns

In [44]:
def verify_outliers(df: pd.DataFrame, col: str) -> bool:
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)
    iqr = q3 - q1

    outlier_report = {}

    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr
        
        
    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
    outlier_report[col] = len(outliers)
        
    if len(outliers) > 0:
        print(f"Coluna '{col}': {len(outliers)} outliers detectados (Limites: {lower_bound:.2f} a {upper_bound:.2f})")
            
    return outlier_report

In [45]:
for coluna in numerical_columns:
    resultado = verify_outliers(df, coluna)

Coluna 'pregnancies': 4 outliers detectados (Limites: -6.50 a 13.50)
Coluna 'glucose': 25 outliers detectados (Limites: 45.00 a 197.00)
Coluna 'blood pressure': 25 outliers detectados (Limites: 47.38 a 96.38)
Coluna 'skin thickness': 87 outliers detectados (Limites: 14.50 a 42.50)
Coluna 'insulin': 362 outliers detectados (Limites: 126.00 a 126.00)
Coluna 'body mass index': 33 outliers detectados (Limites: 16.00 a 48.00)
Coluna 'diabetes pedigree function': 51 outliers detectados (Limites: 0.00 a 0.00)
Coluna 'age': 48 outliers detectados (Limites: 1.00 a 65.00)

# Preparing the dataset for Ingestion Pipelines

In [ ]:
# Add a `source_file` column to the DataFrame
df['source_file'] = 'diabetes-dirty.csv'

In [47]:
# Inspect the final structure of the cleaned dataset

print(f"Formato final do dataset: {df.shape}")

df.info()

Formato final do dataset: (768, 13)
<class 'pandas.core.frame.DataFrame'>
Index: 768 entries, 0 to 767
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   pregnancies                 768 non-null    Int64
 1   glucose                     768 non-null    Int64
 2   blood pressure              768 non-null    Int64
 3   skin thickness              768 non-null    Int64
 4   insulin                     768 non-null    Int64
 5   body mass index             768 non-null    Int64
 6   diabetes pedigree function  768 non-null    Int64
 7   age                         768 non-null    Int64
 8   outcome                     768 non-null    object
 9   clinic region               768 non-null    object
 10  care path                   768 non-null    object
 11  patient segment             768 non-null    object
 12  source_file                 768 non-null    object
dtypes: Int64(8), object(5)
memory usage: 90.0+ KB

In [48]:
# Inspect a small sample
df.sample(5)

,pregnancies,glucose,blood pressure,skin thickness,insulin,body mass index,diabetes pedigree function,age,outcome,clinic region,care path,patient segment,source_file
538,0,119,80,37,126,32,0,23,Negative,North,Routine Follow-up,Adult,diabetes-dirty.csv
211,0,147,85,54,126,42,0,24,Positive,South,Routine Follow-up,Mid-Age,diabetes-dirty.csv
432,1,80,74,11,60,30,0,22,Negative,North,Routine Follow-up,Adult,diabetes-dirty.csv
735,4,95,60,32,126,35,0,28,Negative,South,High-Risk,Adult,diabetes-dirty.csv
299,8,112,72,29,126,23,0,58,Positive,South,Routine Follow-up,Mid-Age,diabetes-dirty.csv

In [51]:
# Export the cleaned dataset to CSV
df.to_csv('../raw/uci-diabetes/cleaned/diabetes-cleaned.csv', index=False)

print("Dataset exportado com sucesso!")

Dataset exportado com sucesso!